apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: app
  replicas: 2 
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: letlejackop/hello-world:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000

